<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Antrian_model extends CI_Model
{

    public $table = 'antrian';
    public $id = 'id_antrian';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_antrian', $q);
	$this->db->or_like('no_antrian', $q);
	$this->db->or_like('id_pasien', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('konfirmasi', $q);
	$this->db->or_like('date_konfirmasi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_antrian', $q);
	$this->db->or_like('no_antrian', $q);
	$this->db->or_like('id_pasien', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('konfirmasi', $q);
	$this->db->or_like('date_konfirmasi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Antrian_model.php */
/* Location: ./application/models/Antrian_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-10-18 07:42:29 */
/* http://harviacode.com */